import React,{useMemo,useState} from 'react';
import {SafeAreaView,View,Text,StyleSheet,Pressable,ScrollView,TextInput,Alert} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {demoConcepts,genres,seedProject} from './app/data';
import {Genre,Project,Scene} from './app/types';

type Screen='home'|'projects'|'characters'|'templates'|'profile'|'genre'|'concepts'|'story'|'storyboard'|'review';
const red='#E50914', bg='#090909', card='#171717', muted='#9b9b9b';
export default function App(){
 const [screen,setScreen]=useState<Screen>('home'); const [genre,setGenre]=useState<Genre>('Horror'); const [project,setProject]=useState<Project|null>(null); const [selectedScene,setSelectedScene]=useState<Scene|null>(null); const [dialogue,setDialogue]=useState('');
 const nav=(s:Screen)=>setScreen(s);
 const start=()=>nav('genre');
 const makeConcept=(c:string)=>{setProject(seedProject(genre,c));nav('story')};
 const scene=useMemo(()=>project?.scenes.find(s=>s.id===selectedScene?.id)||selectedScene,[project,selectedScene]);
 const saveDialogue=()=>{if(!project||!scene)return; const next={...project,scenes:project.scenes.map(s=>s.id===scene.id?{...s,dialogue:[...s.dialogue.slice(0,1),{...s.dialogue[1],text:dialogue}]}:s)};setProject(next);setSelectedScene({...scene,dialogue:next.scenes.find(s=>s.id===scene.id)!.dialogue});setDialogue('');Alert.alert('Saved','Dialogue updated. Re-run QA before approving.');};
 const approve=()=>{if(!project||!scene)return; setProject({...project,scenes:project.scenes.map(s=>s.id===scene.id?{...s,status:'approved',qa:{pass:true,issues:[],speakerErrors:[],continuityErrors:[]}}:s)});Alert.alert('Scene approved','Compilation gate remains locked until all 15 scenes are approved.');};
 return <SafeAreaView style={st.root}><StatusBar style="light"/><ScrollView contentContainerStyle={st.scroll}>
  <View style={st.top}><Text style={st.logo}>AUTO<Text style={{color:red}}>FILM</Text></Text><Text style={st.phase}>AI CINEMA</Text></View>
  {screen==='home'&&<><Hero onPress={start}/><Section title="Continue Watching"><Card title="Demo Project" sub="Episode 1 • Review required" onPress={()=>nav('review')}/></Section><Section title="My Projects"><Card title="Start your first Filipino series" sub="5 episodes • 15 scenes" onPress={start}/></Section></>}
  {screen==='projects'&&<><Title t="My Projects"/><Card title={project?.title||'No projects yet'} sub={project?'In Progress • 15 scenes':'Create a new cinematic project'} onPress={project?()=>nav('storyboard'):start}/></>}
  {screen==='characters'&&<><Title t="Characters"/><Text style={st.muted}>Master Character References</Text>{project?.characters.map(c=><View style={st.row} key={c.id}><View style={st.avatar}><Text style={st.avatarText}>{c.name[0]}</Text></View><View><Text style={st.h3}>{c.name}</Text><Text style={st.muted}>{c.masterRef}</Text><Text style={st.muted}>{c.wardrobeId}</Text></View></View>)||<Card title="No characters yet" sub="Create a project to generate MasterRefs" onPress={start}/>}</>}
  {screen==='templates'&&<><Title t="Templates"/>{genres.map(g=><Card key={g} title={g} sub="Filipino cinematic template" onPress={()=>{setGenre(g);start()}}/>)}</>}
  {screen==='profile'&&<><Title t="Profile"/><Card title="AutoFilm" sub="No login • No user credits"/><Card title="Settings" sub="Provider keys stay on backend"/></>}
  {screen==='genre'&&<><Title t="New Project"/><Text style={st.muted}>Choose your primary genre</Text>{genres.map(g=><Card key={g} title={g} sub={g===genre?'Selected':''} active={g===genre} onPress={()=>setGenre(g)}/>) }<Button text="START STORY" onPress={()=>nav('concepts')}/></>}
  {screen==='concepts'&&<><Title t="Phase 1"/><Text style={st.muted}>Choose 1 of 5 AI concepts. Storyboard is generated automatically after selection.</Text>{demoConcepts.map(c=><Card key={c.title} title={c.title} sub={c.logline} onPress={()=>makeConcept(c.title)}/>)}</>}
  {screen==='story'&&<><Title t="Phase 2 • Story Bible"/><Card title={project?.title||''} sub={project?.genre||''}/><Text style={st.body}>{project?.bible}</Text><Button text="VIEW CHARACTERS" onPress={()=>nav('characters')}/><Button text="OPEN STORYBOARD" onPress={()=>nav('storyboard')}/></>}
  {screen==='storyboard'&&<><Title t="Phase 3 • Storyboard"/><Text style={st.muted}>5 Episodes • 3 scenes each • 90 sec/episode</Text>{[1,2,3,4,5].map(ep=><View key={ep}><Text style={st.h2}>Episode {ep}</Text>{project?.scenes.filter(s=>s.episode===ep).map(s=><Card key={s.id} title={`${s.scene}. ${s.title}`} sub={`${s.durationSec}s • ${s.status}`} onPress={()=>{setSelectedScene(s);setDialogue(s.dialogue[1]?.text||'');nav('review')}}/>)}</View>)}</>}
  {screen==='review'&&scene&&<><Title t="Review & Edit"/><View style={st.videoBox}><Text style={st.videoIcon}>▶</Text><Text style={st.muted}>WAN VIDEO PREVIEW</Text><Text style={st.tiny}>Mock clip • 9:16 • scene {scene.scene}</Text></View><Check label="Character identity" ok/><Check label="Dialogue speaker mapping" ok={scene.dialogue.every(d=>!!project?.characters.find(c=>c.id===d.characterId))}/><Check label="Subtitle / dialogue text" ok/><Check label="Scene continuity" ok/><Text style={st.h2}>Dialogue</Text>{scene.dialogue.map(d=><View key={d.id} style={st.dialogue}><Text style={st.speaker}>{project?.characters.find(c=>c.id===d.characterId)?.name}</Text><Text style={st.body}>{d.text}</Text></View>)}<TextInput value={dialogue} onChangeText={setDialogue} placeholder="Edit second speaker dialogue" placeholderTextColor="#666" style={st.input}/><Button text="SAVE DIALOGUE + QA" onPress={saveDialogue}/><Button text="REGENERATE SCENE" onPress={()=>Alert.alert('Queued','Image → WAN video regeneration would be sent to backend.')}/><Button text="APPROVE SCENE" onPress={approve}/></>}
 </ScrollView><View style={st.nav}>{[['home','Home'],['projects','Projects'],['characters','Characters'],['templates','Templates'],['profile','Profile']].map(([k,l])=><Pressable key={k} onPress={()=>nav(k as Screen)}><Text style={[st.navText,screen===k&&{color:red}]}>{l}</Text></Pressable>)}</View><Pressable style={st.fab} onPress={start}><Text style={st.fabText}>＋</Text></Pressable>
 </SafeAreaView>
}
const Hero=({onPress}:{onPress:()=>void})=><View style={st.hero}><Text style={st.kicker}>CREATE YOUR SERIES</Text><Text style={st.heroTitle}>FILIPINO STORIES.{`\n`}CINEMATICALLY MADE.</Text><Text style={st.muted}>AI storyboard • Character continuity • WAN video • Review before export</Text><Button text="＋ NEW PROJECT" onPress={onPress}/></View>;
const Title=({t}:{t:string})=><Text style={st.title}>{t}</Text>; const Section=({title,children}:{title:string,children:React.ReactNode})=><View><Text style={st.h2}>{title}</Text>{children}</View>; const Card=({title,sub,onPress,active}:{title:string,sub?:string,onPress:()=>void,active?:boolean})=><Pressable onPress={onPress} style={[st.card,active&&st.active]}><Text style={st.h3}>{title}</Text>{sub&&<Text style={st.muted}>{sub}</Text>}</Pressable>; const Button=({text,onPress}:{text:string,onPress:()=>void})=><Pressable onPress={onPress} style={st.button}><Text style={st.buttonText}>{text}</Text></Pressable>; const Check=({label,ok}:{label:string,ok:boolean})=><View style={st.check}><Text style={{color:ok?'#55d17a':'#ffbd4a'}}>{ok?'✓':'⚠'}</Text><Text style={st.body}>{label}</Text></View>;
const st=StyleSheet.create({root:{flex:1,backgroundColor:bg},scroll:{padding:18,paddingBottom:110},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:18},logo:{fontSize:22,fontWeight:'900',color:'#fff',letterSpacing:2},phase:{fontSize:10,color:muted,letterSpacing:2},hero:{padding:22,borderRadius:16,backgroundColor:'#121212',marginBottom:22,borderWidth:1,borderColor:'#2a2a2a'},kicker:{fontSize:11,color:red,fontWeight:'800',letterSpacing:2},heroTitle:{fontSize:29,fontWeight:'900',color:'#fff',marginVertical:12,lineHeight:34},title:{fontSize:30,fontWeight:'900',color:'#fff',marginBottom:12},h2:{fontSize:19,fontWeight:'800',color:'#fff',marginTop:20,marginBottom:10},h3:{fontSize:16,fontWeight:'800',color:'#fff',marginBottom:4},body:{fontSize:14,color:'#ddd',lineHeight:21},muted:{fontSize:12,color:muted,lineHeight:18},tiny:{fontSize:10,color:'#777',marginTop:6},card:{backgroundColor:card,borderRadius:12,padding:16,marginBottom:10,borderWidth:1,borderColor:'#242424'},active:{borderColor:red},button:{backgroundColor:red,borderRadius:10,padding:15,alignItems:'center',marginTop:12},buttonText:{color:'#fff',fontWeight:'900',letterSpacing:1},nav:{position:'absolute',bottom:0,left:0,right:0,height:64,backgroundColor:'#0d0d0d',borderTopWidth:1,borderTopColor:'#222',flexDirection:'row',justifyContent:'space-around',alignItems:'center'},navText:{color:'#777',fontSize:11,fontWeight:'700'},fab:{position:'absolute',right:18,bottom:76,width:58,height:58,borderRadius:29,backgroundColor:red,alignItems:'center',justifyContent:'center',elevation:8},fabText:{color:'#fff',fontSize:30,lineHeight:32},row:{flexDirection:'row',alignItems:'center',padding:14,backgroundColor:card,borderRadius:12,marginTop:10},avatar:{width:52,height:52,borderRadius:26,backgroundColor:'#292929',alignItems:'center',justifyContent:'center',marginRight:12},avatarText:{color:'#fff',fontSize:20,fontWeight:'900'},videoBox:{height:300,borderRadius:14,backgroundColor:'#050505',borderWidth:1,borderColor:'#2a2a2a',alignItems:'center',justifyContent:'center',marginBottom:16},videoIcon:{color:'#fff',fontSize:40},check:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:8},dialogue:{padding:12,backgroundColor:'#141414',borderRadius:10,marginBottom:8},speaker:{color:red,fontWeight:'900',fontSize:11,letterSpacing:1},input:{backgroundColor:'#151515',borderColor:'#333',borderWidth:1,borderRadius:10,padding:13,color:'#fff',marginTop:8}});
