import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import OpenAI from 'openai';
const app=express(); app.use(cors()); app.use(express.json({limit:'2mb'}));
const port=process.env.PORT||3000; const openai=process.env.OPENAI_API_KEY?new OpenAI({apiKey:process.env.OPENAI_API_KEY}):null;
app.get('/health',(_,res)=>res.json({ok:true,service:'autofilm-server',wan:process.env.WAN_MODEL||'wan2.7-i2v'}));
app.post('/api/story/concepts',async(req,res)=>{
 const {genre='Horror',brief='Filipino cinematic short series'}=req.body||{};
 if(!openai)return res.json({mock:true,concepts:Array.from({length:5},(_,i)=>({title:`Concept ${i+1}`,logline:`${genre} story concept ${i+1} — ${brief}`}))});
 try{const r=await openai.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions:'You create viral Filipino cinematic series concepts. Return exactly 5 concepts with natural Filipino loglines.',input:`Genre: ${genre}\nBrief: ${brief}`,text:{format:{type:'json_schema',name:'concepts',strict:true,schema:{type:'object',properties:{concepts:{type:'array',items:{type:'object',properties:{title:{type:'string'},logline:{type:'string'}},required:['title','logline'],additionalProperties:false}}},required:['concepts'],additionalProperties:false}}}});res.json(JSON.parse(r.output_text));}catch(e){res.status(500).json({error:e.message})}
});
app.post('/api/qa/dialogue',(req,res)=>{const {dialogue=[],characters=[]}=req.body||{};const speakerErrors=[];for(const d of dialogue){if(!characters.some(c=>c.id===d.characterId))speakerErrors.push(`Unknown speaker for line ${d.id}`);if(!d.text?.trim())speakerErrors.push(`Empty dialogue line ${d.id}`);}const orderOk=dialogue.every((d,i)=>d.order===i+1);if(!orderOk)speakerErrors.push('Dialogue order mismatch');res.json({pass:speakerErrors.length===0,issues:speakerErrors,speakerErrors,continuityErrors:[]});});
app.post('/api/video/wan',async(req,res)=>{const {imageUrl,prompt,duration=10,resolution='720P',watermark=false}=req.body||{};if(!process.env.ALIBABA_CLOUD_API_KEY||!process.env.WAN_WORKSPACE_ID)return res.json({mock:true,status:'queued',provider:'WAN',model:process.env.WAN_MODEL||'wan2.7-i2v-2026-04-25',message:'WAN credentials/workspace not configured; mock job created.'});
 try{const base=(process.env.WAN_API_BASE||'https://{WorkspaceId}.ap-southeast-1.maas.aliyuncs.com').replace('{WorkspaceId}',process.env.WAN_WORKSPACE_ID);const r=await fetch(`${base}/api/v1/services/aigc/video-generation/video-synthesis`,{method:'POST',headers:{'X-DashScope-Async':'enable','Authorization':`Bearer ${process.env.ALIBABA_CLOUD_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.WAN_MODEL||'wan2.7-i2v-2026-04-25',input:{prompt,media:[{type:'first_frame',url:imageUrl}]},parameters:{resolution,duration:Math.max(2,Math.min(15,Number(duration))),prompt_extend:false,watermark}})});const data=await r.json();if(!r.ok)return res.status(r.status).json(data);res.json({provider:'WAN',status:'queued',taskId:data.output?.task_id||data.task_id,raw:data});}catch(e){res.status(500).json({error:e.message})}
});
app.get('/api/video/wan/:taskId',async(req,res)=>{if(!process.env.ALIBABA_CLOUD_API_KEY||!process.env.WAN_WORKSPACE_ID)return res.json({mock:true,status:'SUCCEEDED',videoUrl:null});try{const base=(process.env.WAN_API_BASE||'https://{WorkspaceId}.ap-southeast-1.maas.aliyuncs.com').replace('{WorkspaceId}',process.env.WAN_WORKSPACE_ID);const r=await fetch(`${base}/api/v1/tasks/${encodeURIComponent(req.params.taskId)}`,{headers:{Authorization:`Bearer ${process.env.ALIBABA_CLOUD_API_KEY}`}});const data=await r.json();res.status(r.status).json(data)}catch(e){res.status(500).json({error:e.message})}});
app.listen(port,()=>console.log(`AutoFilm server listening on ${port}`));
